### ISSUE TITLE
BCM57786 Ethernet for macOS 11+

### ISSUE THREAD

**Issue by samuelnotfound** [Gilberto-Mascena/Laptop-Acer-E1-572#1]
[Link](https://github.com/unitedastronomer/ModifiedAppleBCM5701Family)

**Comment by Gilberto-Mascena** [comment]
Regarding BCM57786 Ethernet for macOS 11+, I will need more time to evaluate and finally give you an answer, thanks in advance!

**Comment by Gilberto-Mascena** [comment]
Dear, unitedastronomer I have indeed verified that your suggestions regarding BCM57786 Ethernet for macOS 11+ are in fact appropriate and have been implemented as you can see in the commit: f868ec0.
