### ISSUE TITLE
[Fix] Wake from sleep

### ISSUE THREAD

**Issue by samuelnotfound** [Gilberto-Mascena/Laptop-Acer-E1-572#2]
I randomly tried to combine multiple fixes for sleep at the same time, and I somehow manage to get it to work. This had work for me, and I wonder if you could try it too?

I have added a RTCMemoryFixup.kext and an NVRAM entry for rtc-blacklist at "B2", this solves the issue when waking up from sleep causes it to restart. 
I also have added SSDT-GPRW and the ACPI rename patches that comes with it, without this (and with only an rtc-blacklist) the laptop won't wake from sleep and would remain off.

**Comment by Gilberto-Mascena** [comment]
Dear unitedastronomer:
Thank you for sharing your knowledge.
Your solution to correct sleep really proved to be correct in my tests.
That's why they were implemented as can be seen in commit: 502cb53.
