### ISSUE TITLE
Support for Aspire E1-570 too?

### ISSUE THREAD

**Issue by FStechek** [Gilberto-Mascena/Laptop-Acer-E1-572#3]
I wan't to have hackintosh on my Aspire E1-570
Because it has same Ethernet and Wifi specs
and there is a guy who had success with hackintosh by firstly building mojave up to big sur
*u/victorthejew*

So about to support?

**Comment by Gilberto-Mascena** [comment]
Dear FStechek, you can try with this efi, but you will need to make some modifications, I recommend extracting your DSDT and generating a hardware report with Aida64.
   The DSDT will be used for SSDT corrections and the Aida64 report will help you find out exactly what your hardware is, if you need a guide, I recommend the opencore installation guide.

**Comment by FStechek** [comment]
tanks i will fork it then
also thanks for your sharing your build it helps us
