### ISSUE TITLE
EFI Error - need help

### ISSUE THREAD

**Issue by Birdabo404** [Gilberto-Mascena/Laptop-Acer-E1-572#4]
I'm am currently trying to install a hackintosh on my ACER ASPIRE E1 - 572, same hardware as yours. 

I tried your EFI but when I boot the usb installer it just goes to a black screen. Is there any changes I need to do BEFORE dropping your EFI to my usb?

**Comment by Birdabo404** [comment]
The trackpad is not recognized in the control center as well, Hope you can reply.

**Comment by Gilberto-Mascena** [comment]
Dear Birdabo404, firstly you need to have the dump of your clean DSDT and an Aida64 hardware report, the clean DSDT for your SSDT paths and the Aida64 hardware report for a complete x-ray of your hardware, remembering that mine toush pad and keyboard is PS/2 connection, avoid configurators and ready-made images distributed on the internet, or use macOS Recovery.
Hope this helps!
Cordially: Gilberto Mascena.
